export const SITE_LIST_SUCCESS = 'SITE_LIST_SUCCESS'
export const SITE_LIST_REQUEST = 'SITE_LIST_REQUEST'
export const SITE_LIST_FAIL = 'SITE_LIST_FAIL'

export const SITE_UPDATE_SUCCESS = 'SITE_UPDATE_SUCCESS'
export const SITE_UPDATE_REQUEST = 'SITE_UPDATE_REQUEST'
export const SITE_UPDATE_FAIL = 'SITE_UPDATE_FAIL'
export const SITE_UPDATE_RESET = 'SITE_UPDATE_RESET'